### ISSUE TITLE
Hotch() sometimes generates an empty graph

### ISSUE THREAD

**Issue by pnomolos** [splattael/hotch#2]
When testing the difference in complexity between ActiveRecord and rom-sql, I found that running `Hotch()` was generating nothing.  See https://gist.github.com/pnomolos/56684748c43a0ab68c8f for the full example (the ActiveRecord one works fine, it's only the ROM one that doesn't).

**Comment by splattael** [comment]
@pnomolos Thanks for reporting!

Empty graphs might possibly mean that stackprof does not have enough cycles to profile because the program runs too fast.

Did you try to wrap your calls with `100.times { ... }`?

**Comment by pnomolos** [comment]
@splattael I just did and that gave me a profile, thanks :)

**Comment by pnomolos** [comment]
@splattael Maybe adding a note to the README about that possible case would be helpful for others?

**Comment by splattael** [comment]
@pnomolos You are welcome! Great it worked for you :-) :+1:

**Comment by splattael** [comment]
@pnomolos Good idea! PRs are always welcome :) :green_heart:
